export type ProductStatus = "published" | "draft" | "hidden";

export type Product = {
  id: string;
  name: string;
  name_zh: string | null;
  slug: string;
  category: string | null;
  category_zh: string | null;
  short_description: string | null;
  short_description_zh: string | null;
  full_description: string | null;
  full_description_zh: string | null;
  specifications: string | null;
  specifications_zh: string | null;
  material: string | null;
  origin: string | null;
  status: ProductStatus;
  featured: boolean;
  sort_order: number;
  main_image_url: string | null;
  gallery_urls: string[] | null;
  video_url: string | null;
  pdf_url: string | null;
  show_quote_button: boolean | null;
  created_at: string;
  updated_at: string;
};

export type ProductPayload = {
  name: string;
  name_zh: string | null;
  slug: string;
  category: string | null;
  category_zh: string | null;
  short_description: string | null;
  short_description_zh: string | null;
  full_description: string | null;
  full_description_zh: string | null;
  specifications: string | null;
  specifications_zh: string | null;
  material: string | null;
  origin: string | null;
  status: ProductStatus;
  featured: boolean;
  sort_order: number;
  main_image_url: string | null;
  gallery_urls: string[] | null;
  video_url: string | null;
  pdf_url: string | null;
  show_quote_button: boolean;
};
