export type SiteSettings = {
  id?: string;
  whatsapp_url: string;
  whatsapp_number: string;
  email: string;
  company_name: string;
  company_name_zh?: string | null;
  logo_url?: string | null;
  favicon_url?: string | null;
  show_language_selector?: boolean | null;
  show_admin_button?: boolean | null;
  show_quote_button?: boolean | null;
  header_quote_text?: string | null;
  header_quote_text_zh?: string | null;
  header_quote_url?: string | null;
  hero_badge: string;
  hero_badge_zh?: string | null;
  hero_title: string;
  hero_title_zh?: string | null;
  hero_subtitle: string;
  hero_subtitle_zh?: string | null;
  hero_primary_button_text: string;
  hero_primary_button_text_zh?: string | null;
  hero_primary_button_url: string;
  hero_secondary_button_text: string;
  hero_secondary_button_text_zh?: string | null;
  hero_secondary_button_url: string;
  hero_image_url: string;
  hero_mobile_image_url: string;
  show_hero_primary_button: boolean;
  show_hero_secondary_button: boolean;
  catalog_title: string;
  catalog_title_zh?: string | null;
  catalog_subtitle: string;
  catalog_subtitle_zh?: string | null;
  catalog_pdf_url: string;
  floating_whatsapp_number?: string | null;
  floating_whatsapp_message?: string | null;
  floating_whatsapp_message_zh?: string | null;
  floating_whatsapp_aria_label?: string | null;
  floating_whatsapp_aria_label_zh?: string | null;
  show_floating_whatsapp?: boolean | null;
  floating_whatsapp_position?: string | null;
  floating_whatsapp_size?: string | null;
  seo_title?: string | null;
  seo_title_zh?: string | null;
  seo_description?: string | null;
  seo_description_zh?: string | null;
  seo_keywords?: string | null;
  seo_og_title?: string | null;
  seo_og_description?: string | null;
  seo_image_url?: string | null;
  seo_canonical?: string | null;
  seo_indexable?: boolean | null;
  created_at?: string;
  updated_at?: string;
};
